# Generated by Django 2.1.2 on 2018-10-10 18:58

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(choices=[('received', 'RECEIVED'), ('started', 'STARTED'), ('failed', 'FAILED'), ('submitted', 'SUBMITTED'), ('completed', 'COMPLETED')], default='received', max_length=50, protected=True)),
                ('messageId', models.CharField(max_length=64)),
                ('senderId', models.CharField(max_length=64)),
                ('recipientId', models.CharField(max_length=64)),
                ('messageType', models.CharField(choices=[('push', 'PUSH'), ('sms', 'SMS')], max_length=64)),
                ('channel', models.CharField(choices=[('africa-is-talking', 'AT'), ('google', 'GOOGLE'), ('smpp', 'SMPP')], max_length=64)),
                ('message', models.CharField(max_length=200)),
                ('priority', models.CharField(default='', max_length=64)),
                ('status', models.CharField(default='', max_length=64)),
                ('callback', models.CharField(default='', max_length=200)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
