# Generated by Django 2.1.2 on 2018-10-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='priority',
            field=models.CharField(default='', max_length=64, null=True),
        ),
    ]
