# Generated by Django 2.1.2 on 2018-10-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181010_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='priority',
            field=models.CharField(default='normal', max_length=64),
        ),
    ]
