# Generated by Django 2.1.2 on 2018-10-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181010_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='priority',
            field=models.CharField(blank=True, default='normal', max_length=64),
        ),
    ]
