# Generated by Django 2.1.2 on 2018-10-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181010_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='messageId',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='priority',
            field=models.CharField(blank=True, default='normal', max_length=64, null=True),
        ),
    ]
